const VERSION="5.0 Complete";
const SHEETS={RECIPES:"Recipes",PLANNER:"Planner",SHOPPING:"Shopping",PANTRY:"Pantry",LOGS:"ImportLog"};
const HEADERS={
  Recipes:["id","createdAt","updatedAt","title","description","timeMinutes","timeText","servings","calories","protein","carbs","fat","difficulty","category","tagsJson","ingredientsJson","stepsJson","source","sourceType","sourceAuthor","originalVideoUrl","imageFileId","imageUrl","videoUrl","favorite","rating","notes","variantOf","appliancesJson"],
  Planner:["id","weekStart","day","meal","recipeId","servings"],
  Shopping:["id","weekStart","item","quantity","unit","category","done","sourceRecipeIdsJson"],
  Pantry:["id","item","quantity","unit","category","updatedAt"],
  ImportLog:["createdAt","source","status","message","recipeId"]
};
function doGet(){return json_({ok:true,data:{name:"RicettaGo API",version:VERSION}})}
function doPost(e){try{const p=JSON.parse((e.postData&&e.postData.contents)||"{}");if(!ACTIONS[p.action])throw new Error("Azione non valida: "+p.action);return json_({ok:true,data:ACTIONS[p.action](p)})}catch(err){return json_({ok:false,error:String(err&&err.message||err)})}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function props_(){return PropertiesService.getScriptProperties()}
function setupRicettaGo(){const p=props_();let ss=p.getProperty("SPREADSHEET_ID")?SpreadsheetApp.openById(p.getProperty("SPREADSHEET_ID")):SpreadsheetApp.create("RicettaGo Database");p.setProperty("SPREADSHEET_ID",ss.getId());Object.keys(HEADERS).forEach(n=>ensureHeaders_(ss,n,HEADERS[n]));let f=p.getProperty("DRIVE_FOLDER_ID");if(!f){const folder=DriveApp.createFolder("RicettaGo Immagini");f=folder.getId();p.setProperty("DRIVE_FOLDER_ID",f)}Logger.log("Foglio: "+ss.getUrl());Logger.log("Drive: https://drive.google.com/drive/folders/"+f);return {spreadsheetId:ss.getId(),folderId:f}}
function ss_(){const id=props_().getProperty("SPREADSHEET_ID");if(!id)throw new Error("Esegui setupRicettaGo() una volta dall'editor Apps Script.");return SpreadsheetApp.openById(id)}
function ensureHeaders_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);return sh}let current=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),1)).getValues()[0].filter(String);const missing=headers.filter(h=>current.indexOf(h)<0);if(missing.length){sh.getRange(1,current.length+1,1,missing.length).setValues([missing])}return sh}
function sheet_(name){return ensureHeaders_(ss_(),name,HEADERS[name])}
function rows_(name){const sh=sheet_(name),v=sh.getDataRange().getValues();if(v.length<2)return [];const h=v[0];return v.slice(1).map((r,i)=>({__row:i+2,...Object.fromEntries(h.map((x,j)=>[x,r[j]]))})).filter(r=>Object.keys(r).some(k=>k!=="__row"&&r[k]!==""))}
function append_(name,obj){const sh=sheet_(name),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];sh.appendRow(h.map(k=>obj[k]===undefined?"":obj[k]));return obj}
function update_(name,row,obj){const sh=sheet_(name),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];Object.keys(obj).forEach(k=>{const c=h.indexOf(k);if(c>=0)sh.getRange(row,c+1).setValue(obj[k])})}
function delRow_(name,row){sheet_(name).deleteRow(row)}
function safeJson_(s,def){try{return JSON.parse(s||"")}catch(e){return def}}
function bool_(v){return v===true||String(v).toLowerCase()==="true"}
function normIng_(x){if(typeof x==="string")return {name:x,quantity:"",unit:"",note:"",display:x};return {name:x.name||x.ingredient||x.display||"",quantity:x.quantity===undefined?"":x.quantity,unit:x.unit||"",note:x.note||"",display:x.display||""}}
function recipe_(r){return {...r,favorite:bool_(r.favorite),rating:Number(r.rating)||0,timeMinutes:Number(r.timeMinutes)||0,servings:Number(r.servings)||1,calories:Number(r.calories)||0,protein:Number(r.protein)||0,carbs:Number(r.carbs)||0,fat:Number(r.fat)||0,tags:safeJson_(r.tagsJson,[]),ingredients:safeJson_(r.ingredientsJson,[]).map(normIng_),steps:safeJson_(r.stepsJson,[]),appliances:safeJson_(r.appliancesJson,[])}}
function listRecipes_(){return rows_(SHEETS.RECIPES).map(recipe_).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
function getRecipe_(id){const r=rows_(SHEETS.RECIPES).find(x=>String(x.id)===String(id));if(!r)throw new Error("Ricetta non trovata");return recipe_(r)}
function log_(source,status,message,id){append_(SHEETS.LOGS,{createdAt:new Date().toISOString(),source:source||"",status,message:message||"",recipeId:id||""})}
function openAIJson_(messages,model){const key=props_().getProperty("OPENAI_API_KEY");if(!key)throw new Error("Manca OPENAI_API_KEY nelle Script Properties.");const m=model||props_().getProperty("OPENAI_MODEL")||"gpt-5-mini";const payload={model:m,messages,response_format:{type:"json_object"}};const res=UrlFetchApp.fetch("https://api.openai.com/v1/chat/completions",{method:"post",contentType:"application/json",headers:{Authorization:"Bearer "+key},payload:JSON.stringify(payload),muteHttpExceptions:true});const txt=res.getContentText();let j;try{j=JSON.parse(txt)}catch(e){throw new Error("Risposta OpenAI non valida")};if(res.getResponseCode()>=300)throw new Error((j.error&&j.error.message)||"Errore OpenAI");return JSON.parse(j.choices[0].message.content)}
function imageParts_(urls){return (urls||[]).filter(Boolean).slice(0,4).map(u=>({type:"image_url",image_url:{url:u}}))}
function saveDataImage_(dataUrl){if(!dataUrl)return {id:"",url:""};const m=String(dataUrl).match(/^data:(.+);base64,(.+)$/);if(!m)throw new Error("Immagine non valida");const blob=Utilities.newBlob(Utilities.base64Decode(m[2]),m[1],"ricetta-"+Date.now()+".jpg");return saveBlob_(blob)}
function saveBlob_(blob){const folder=DriveApp.getFolderById(props_().getProperty("DRIVE_FOLDER_ID"));const f=folder.createFile(blob);try{f.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(e){}return {id:f.getId(),url:"https://drive.google.com/thumbnail?id="+f.getId()+"&sz=w1600"}}
function saveRemoteImage_(url){if(!url)return {id:"",url:""};try{const r=UrlFetchApp.fetch(url,{muteHttpExceptions:true,followRedirects:true,headers:{"User-Agent":"Mozilla/5.0"}});if(r.getResponseCode()<200||r.getResponseCode()>=400)return {id:"",url:url};return saveBlob_(r.getBlob().setName("ricetta-web-"+Date.now()))}catch(e){return {id:"",url:url}}}
function isUrl_(s){return /^https?:\/\/\S+$/i.test(String(s||"").trim())}
function sourceType_(s){s=String(s||"");if(/instagram\.com/i.test(s))return "instagram";if(/youtube\.com|youtu\.be/i.test(s))return "youtube";if(/^https?:/i.test(s))return "web";return "text"}
function decodeHtml_(s){return String(s||"").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&nbsp;/g," ")}
function stripHtml_(h){return decodeHtml_(String(h||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ")).trim()}
function recipeNode_(o){if(!o)return null;if(Array.isArray(o)){for(const x of o){const r=recipeNode_(x);if(r)return r}return null}if(typeof o==="object"){const t=o["@type"];if(t==="Recipe"||(Array.isArray(t)&&t.indexOf("Recipe")>=0))return o;if(o["@graph"]){const r=recipeNode_(o["@graph"]);if(r)return r}for(const k in o){if(k!=="@context"&&typeof o[k]==="object"){const r=recipeNode_(o[k]);if(r)return r}}}return null}
function steps_(v){if(!v)return [];if(typeof v==="string")return v.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(Array.isArray(v))return v.flatMap(steps_);if(typeof v==="object"){if(v.text)return [String(v.text)];if(v.itemListElement)return steps_(v.itemListElement)}return []}
function image_(v){if(!v)return "";if(typeof v==="string")return v;if(Array.isArray(v))return image_(v[0]);if(typeof v==="object")return v.url||v.contentUrl||"";return ""}
function number_(v){const m=String(v||"").replace(",",".").match(/[\d.]+/);return m?Number(m[0]):0}
function fetchWeb_(url){const r=UrlFetchApp.fetch(url,{followRedirects:true,muteHttpExceptions:true,headers:{"User-Agent":"Mozilla/5.0 (compatible; RicettaGo/5.0)","Accept-Language":"it-IT,it;q=0.9"}});if(r.getResponseCode()<200||r.getResponseCode()>=400)throw new Error("Il sito non consente la lettura automatica (HTTP "+r.getResponseCode()+")");const html=r.getContentText(),rx=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let rec=null,m;while((m=rx.exec(html))!==null){try{rec=recipeNode_(JSON.parse(decodeHtml_(m[1]).trim()));if(rec)break}catch(e){}}let title=rec&&rec.name||"",img=image_(rec&&rec.image),ing=rec&&rec.recipeIngredient||[],st=steps_(rec&&rec.recipeInstructions),nut=rec&&rec.nutrition||{};if(!title){const x=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);title=x?stripHtml_(x[1]):""}if(!img){const x=html.match(/<meta[^>]+(?:property|name)=["']og:image["'][^>]+content=["']([^"']+)["']/i)||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']og:image["']/i);img=x?decodeHtml_(x[1]):""}return {type:"web",url,title,image:img,visualUrls:[img],ingredients:ing,steps:st,servings:number_(rec&&rec.recipeYield),time:rec&&(rec.totalTime||rec.cookTime||rec.prepTime)||"",nutrition:nut,text:stripHtml_(html).slice(0,50000),author:typeof(rec&&rec.author)==="object"?(rec.author.name||""):(rec&&rec.author||""),structured:!!rec}}
function meta_(html,key){const e=String(key).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const a=html.match(new RegExp("<meta[^>]+(?:property|name)=[\\\"']"+e+"[\\\"'][^>]+content=[\\\"']([^\\\"']*)[\\\"']","i"));const b=html.match(new RegExp("<meta[^>]+content=[\\\"']([^\\\"']*)[\\\"'][^>]+(?:property|name)=[\\\"']"+e+"[\\\"']","i"));return decodeHtml_((a||b||[])[1]||"")}
function youtube_(url){const r=UrlFetchApp.fetch(url,{followRedirects:true,muteHttpExceptions:true,headers:{"User-Agent":"Mozilla/5.0","Accept-Language":"it-IT,it;q=0.9"}}),html=r.getContentText();let title=meta_(html,"og:title"),description=meta_(html,"og:description"),image=meta_(html,"og:image"),transcript="";const d=html.match(/"shortDescription":"((?:\\.|[^"\\])*)"/);if(d)try{description=JSON.parse('"'+d[1].replace(/"/g,'\\"')+'"')}catch(e){}const cm=html.match(/"captionTracks":(\[[\s\S]*?\]),"audioTracks"/);if(cm)try{const tracks=JSON.parse(cm[1].replace(/\\u0026/g,"&"));if(tracks.length){const cr=UrlFetchApp.fetch(tracks[0].baseUrl+"&fmt=json3",{muteHttpExceptions:true});if(cr.getResponseCode()<400){const cj=JSON.parse(cr.getContentText()),lines=[];(cj.events||[]).forEach(ev=>{const t=(ev.segs||[]).map(s=>s.utf8||"").join("").replace(/\n/g," ").trim();if(t)lines.push(t)});transcript=lines.join(" ")}}}catch(e){}return {type:"youtube",url,title,description,transcript,image,visualUrls:[image],author:"",videoUrl:url}}
function apifyRun_(actor,payload){const token=props_().getProperty("APIFY_API_TOKEN");if(!token)throw new Error("Manca APIFY_API_TOKEN nelle Script Properties.");const endpoint="https://api.apify.com/v2/acts/"+actor+"/run-sync-get-dataset-items?token="+encodeURIComponent(token);const r=UrlFetchApp.fetch(endpoint,{method:"post",contentType:"application/json",payload:JSON.stringify(payload),muteHttpExceptions:true,followRedirects:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error("Apify HTTP "+r.getResponseCode()+": "+r.getContentText().slice(0,250));return JSON.parse(r.getContentText()||"[]")}
function instagram_(url){const actor=props_().getProperty("APIFY_INSTAGRAM_ACTOR")||"apify~instagram-reel-scraper";let arr=apifyRun_(actor,{username:[url],resultsLimit:1});if(!arr.length)arr=apifyRun_(actor,{startUrls:[{url:url}],resultsLimit:1});if(!arr.length)throw new Error("Apify non ha restituito dati per questo Reel.");let x=arr.find(i=>String(i.inputUrl||i.url||"").indexOf(url.split('?')[0].replace(/\/$/,''))>=0)||arr[0];if(x.error)throw new Error(x.errorDescription||x.error);const transcript=typeof x.transcript==="string"?x.transcript:((x.transcript&&x.transcript.text)||"");const images=[x.displayUrl].concat(Array.isArray(x.images)?x.images:[]).filter(Boolean);return {type:"instagram",url:url,title:x.ownerFullName||x.ownerUsername||"Instagram Reel",description:x.caption||"",transcript,image:x.displayUrl||images[0]||"",visualUrls:images.slice(0,4),author:x.ownerUsername||x.ownerFullName||"",videoUrl:x.videoUrl||x.downloadedVideoUrl||"",originalVideoUrl:url}}
function collectSource_(source){if(!isUrl_(source))return {type:"text",url:"",title:"",description:String(source||""),transcript:"",image:"",visualUrls:[],author:"",videoUrl:""};if(/instagram\.com/i.test(source))return instagram_(source);if(/youtube\.com|youtu\.be/i.test(source))return youtube_(source);return fetchWeb_(source)}
function recipePrompt_(info){let material="";if(info.type==="web")material=["URL: "+info.url,"TITOLO: "+info.title,"DATI STRUTTURATI: "+(info.structured?"SI":"NO"),"INGREDIENTI:\n"+(info.ingredients||[]).join("\n"),"PROCEDIMENTO:\n"+(info.steps||[]).join("\n"),"NUTRIZIONE: "+JSON.stringify(info.nutrition||{}),"TESTO PAGINA:\n"+(info.text||"")].join("\n\n");else material=["FONTE: "+info.type,"URL: "+(info.url||""),"TITOLO: "+(info.title||""),"CAPTION/DESCRIZIONE:\n"+(info.description||""),"TRASCRIZIONE:\n"+(info.transcript||"")].join("\n\n");return `Estrai una ricetta fedele SOLTANTO dalle informazioni disponibili. Non inventare ingredienti o passaggi. Le immagini allegate sono fotogrammi/copertine: usa solo testo o elementi chiaramente visibili, senza deduzioni speculative. Se le quantità non sono presenti, lascia quantity vuoto invece di inventarle. Classifica automaticamente la ricetta. Restituisci SOLO JSON valido con questa struttura:\n{"title":"","description":"breve","timeMinutes":0,"timeText":"","servings":0,"calories":0,"protein":0,"carbs":0,"fat":0,"difficulty":"Facile|Media|Difficile","category":"Primi|Secondi|Dolci|Pane e pizza|Contorni|Antipasti|Colazione|Snack|Bevande|Altro","tags":["..."],"ingredients":[{"name":"","quantity":"","unit":"","note":""}],"steps":["..."],"appliances":["Bimby","Friggitrice ad aria"]}. I nutrienti possono essere stimati solo se ingredienti e quantità sono sufficienti.\n\n${material}`}
function saveRecipe_(r,meta){const now=new Date().toISOString(),id=Utilities.getUuid();const obj={id,createdAt:now,updatedAt:now,title:r.title||meta.title||"Ricetta",description:r.description||"",timeMinutes:r.timeMinutes||0,timeText:r.timeText||"",servings:r.servings||1,calories:r.calories||0,protein:r.protein||0,carbs:r.carbs||0,fat:r.fat||0,difficulty:r.difficulty||"",category:r.category||"Altro",tagsJson:JSON.stringify(r.tags||[]),ingredientsJson:JSON.stringify((r.ingredients||[]).map(normIng_)),stepsJson:JSON.stringify(r.steps||[]),source:meta.source||"",sourceType:meta.sourceType||"",sourceAuthor:meta.sourceAuthor||"",originalVideoUrl:meta.originalVideoUrl||"",imageFileId:meta.imageFileId||"",imageUrl:meta.imageUrl||"",videoUrl:meta.videoUrl||"",favorite:false,rating:0,notes:"",variantOf:meta.variantOf||"",appliancesJson:JSON.stringify(r.appliances||[])};append_(SHEETS.RECIPES,obj);return recipe_(obj)}
function importRecipe_(p){const source=String(p.source||"").trim();if(!source&&!p.imageData)throw new Error("Inserisci link, testo o foto.");if(source&&isUrl_(source)){const ex=rows_(SHEETS.RECIPES).find(x=>String(x.source)===source);if(ex)return {id:ex.id,duplicate:true}}try{const info=collectSource_(source),content=[{type:"text",text:recipePrompt_(info)}];if(p.imageData)content.push({type:"image_url",image_url:{url:p.imageData}});else content.push(...imageParts_(info.visualUrls));const r=openAIJson_([{role:"system",content:"Sei un assistente culinario preciso. Devi restituire JSON valido e non inventare dati mancanti."},{role:"user",content}]);if(!r.ingredients||!r.ingredients.length||!r.steps||!r.steps.length)throw new Error("La fonte è stata letta, ma non contiene abbastanza informazioni per una ricetta completa.");const img=p.imageData?saveDataImage_(p.imageData):saveRemoteImage_(info.image);const saved=saveRecipe_(r,{source,sourceType:info.type,sourceAuthor:info.author||"",originalVideoUrl:(info.type==="instagram"||info.type==="youtube")?source:"",imageFileId:img.id,imageUrl:img.url,videoUrl:info.videoUrl||""});log_(source,"OK","Importata",saved.id);return {id:saved.id,duplicate:false}}catch(e){log_(source,"ERROR",String(e.message||e),"");throw e}}
function smartSearch_(q){const rec=listRecipes_();if(!rec.length)return [];const compact=rec.slice(0,150).map(r=>({id:r.id,title:r.title,time:r.timeMinutes,category:r.category,tags:r.tags,ingredients:r.ingredients.map(i=>i.name).slice(0,12),calories:r.calories}));try{const j=openAIJson_([{role:"system",content:"Seleziona le ricette che soddisfano meglio la richiesta. Restituisci JSON {ids:[...]} senza inventare ID."},{role:"user",content:"Richiesta: "+q+"\nRicette: "+JSON.stringify(compact)}]);return (j.ids||[]).filter(id=>compact.some(x=>x.id===id))}catch(e){const t=String(q).toLowerCase();return rec.filter(r=>JSON.stringify(r).toLowerCase().includes(t)).map(r=>r.id)}}
function pantrySuggestions_(){const pantry=rows_(SHEETS.PANTRY).map(x=>String(x.item).toLowerCase()),rec=listRecipes_();return rec.map(r=>{const ing=r.ingredients.map(i=>String(i.name).toLowerCase());let hit=ing.filter(i=>pantry.some(p=>i.includes(p)||p.includes(i))).length;return {id:r.id,score:ing.length?hit/ing.length:0,hit}}).filter(x=>x.hit>0).sort((a,b)=>b.score-a.score||b.hit-a.hit).slice(0,12).map(x=>x.id)}
function createFromPantry_(){const p=rows_(SHEETS.PANTRY);if(!p.length)throw new Error("Aggiungi prima qualche ingrediente in dispensa.");const j=openAIJson_([{role:"system",content:"Crea una ricetta pratica usando soprattutto gli ingredienti disponibili. Output JSON con lo stesso schema ricetta richiesto."},{role:"user",content:"Dispensa: "+JSON.stringify(p.map(x=>({item:x.item,quantity:x.quantity,unit:x.unit})) )+"\nRestituisci JSON con title,description,timeMinutes,timeText,servings,calories,protein,carbs,fat,difficulty,category,tags,ingredients[{name,quantity,unit,note}],steps,appliances."}]);const r=saveRecipe_(j,{source:"pantry://generated",sourceType:"ai",sourceAuthor:"RicettaGo AI"});return {id:r.id}}
function convertRecipe_(id,mode){const r=getRecipe_(id),label=mode==="bimby"?"Bimby":"friggitrice ad aria";const j=openAIJson_([{role:"system",content:"Adatta fedelmente una ricetta all'apparecchio indicato. Non modificare inutilmente ingredienti e quantità. Output JSON ricetta completo."},{role:"user",content:"Apparecchio: "+label+"\nRicetta: "+JSON.stringify(r)}]);j.title=(j.title||r.title)+" • "+label;const x=saveRecipe_(j,{source:r.source,sourceType:r.sourceType,sourceAuthor:r.sourceAuthor,originalVideoUrl:r.originalVideoUrl,imageUrl:r.imageUrl,imageFileId:r.imageFileId,videoUrl:r.videoUrl,variantOf:r.id});return {id:x.id}}
function generateMealPlan_(p){const rec=listRecipes_();if(!rec.length)throw new Error("Salva prima qualche ricetta.");const compact=rec.slice(0,120).map(r=>({id:r.id,title:r.title,category:r.category,tags:r.tags,calories:r.calories}));const j=openAIJson_([{role:"system",content:"Crea un menu settimanale equilibrato usando SOLO gli ID forniti. Restituisci JSON {items:[{day,meal,recipeId,servings}]}. day deve essere uno dei 7 giorni italiani e meal uno tra Colazione,Pranzo,Cena. Puoi lasciare vuoti pasti se non ci sono ricette adatte."},{role:"user",content:"Preferenze: "+(p.preferences||"nessuna")+"\nRicette: "+JSON.stringify(compact)}]);const sh=sheet_(SHEETS.PLANNER),old=rows_(SHEETS.PLANNER).filter(x=>String(x.weekStart)===String(p.weekStart)).sort((a,b)=>b.__row-a.__row);old.forEach(x=>sh.deleteRow(x.__row));(j.items||[]).forEach(x=>{if(compact.some(r=>r.id===x.recipeId))append_(SHEETS.PLANNER,{id:Utilities.getUuid(),weekStart:p.weekStart,day:x.day,meal:x.meal,recipeId:x.recipeId,servings:x.servings||1})});return true}
function buildShopping_(p){const plan=rows_(SHEETS.PLANNER).filter(x=>String(x.weekStart)===String(p.weekStart)),rec=listRecipes_(),materials=[];plan.forEach(x=>{const r=rec.find(y=>y.id===x.recipeId);if(!r)return;const factor=(Number(x.servings)||Number(r.servings)||1)/(Number(r.servings)||1);r.ingredients.forEach(i=>materials.push({recipeId:r.id,name:i.name,quantity:i.quantity,unit:i.unit,factor}))});if(!materials.length)throw new Error("Il menu della settimana è vuoto.");let items=[];try{const j=openAIJson_([{role:"system",content:"Normalizza e aggrega una lista della spesa. Somma solo quantità con unità compatibili. Restituisci JSON {items:[{item,quantity,unit,category,sourceRecipeIds:[...]}]}. Categorie: Ortofrutta,Carne,Pesce,Latticini,Uova,Panetteria,Dispensa,Surgelati,Bevande,Altro."},{role:"user",content:JSON.stringify(materials)}]);items=j.items||[]}catch(e){const m={};materials.forEach(x=>{const k=(x.name+"|"+x.unit).toLowerCase();if(!m[k])m[k]={item:x.name,quantity:0,unit:x.unit,category:"Altro",sourceRecipeIds:[]};const q=Number(String(x.quantity).replace(',','.'));if(!isNaN(q))m[k].quantity+=q*x.factor;else m[k].quantity="";m[k].sourceRecipeIds.push(x.recipeId)});items=Object.values(m)}const sh=sheet_(SHEETS.SHOPPING),old=rows_(SHEETS.SHOPPING).filter(x=>String(x.weekStart)===String(p.weekStart)).sort((a,b)=>b.__row-a.__row);old.forEach(x=>sh.deleteRow(x.__row));items.forEach(x=>append_(SHEETS.SHOPPING,{id:Utilities.getUuid(),weekStart:p.weekStart,item:x.item,quantity:x.quantity,unit:x.unit,category:x.category||"Altro",done:false,sourceRecipeIdsJson:JSON.stringify(x.sourceRecipeIds||[])}));return items.length}
const ACTIONS={
 status:()=>({name:"RicettaGo",version:VERSION,recipes:rows_(SHEETS.RECIPES).length}),
 importRecipe:importRecipe_,listRecipes:()=>listRecipes_(),getRecipe:p=>getRecipe_(p.id),smartSearch:p=>smartSearch_(p.query),
 updateRecipeMeta:p=>{const r=rows_(SHEETS.RECIPES).find(x=>x.id===p.id);if(!r)throw new Error("Ricetta non trovata");const u={updatedAt:new Date().toISOString()};["favorite","rating","notes"].forEach(k=>{if(p[k]!==undefined)u[k]=p[k]});update_(SHEETS.RECIPES,r.__row,u);return true},
 deleteRecipe:p=>{const r=rows_(SHEETS.RECIPES).find(x=>x.id===p.id);if(!r)return true;if(r.imageFileId)try{DriveApp.getFileById(r.imageFileId).setTrashed(true)}catch(e){}delRow_(SHEETS.RECIPES,r.__row);return true},
 convertRecipe:p=>convertRecipe_(p.id,p.mode),
 getPantry:()=>rows_(SHEETS.PANTRY).map(x=>({...x,quantity:Number(x.quantity)||x.quantity})),addPantry:p=>append_(SHEETS.PANTRY,{id:Utilities.getUuid(),item:p.item,quantity:p.quantity||"",unit:p.unit||"",category:p.category||"",updatedAt:new Date().toISOString()}),removePantry:p=>{const x=rows_(SHEETS.PANTRY).find(r=>r.id===p.id);if(x)delRow_(SHEETS.PANTRY,x.__row);return true},pantrySuggestions:()=>pantrySuggestions_(),createFromPantry:()=>createFromPantry_(),
 getPlanner:p=>({plan:rows_(SHEETS.PLANNER).filter(x=>String(x.weekStart)===String(p.weekStart)),recipes:listRecipes_()}),saveMeal:p=>{const ex=rows_(SHEETS.PLANNER).find(x=>String(x.weekStart)===String(p.weekStart)&&x.day===p.day&&x.meal===p.meal);const r=getRecipe_(p.recipeId);if(ex)update_(SHEETS.PLANNER,ex.__row,{recipeId:p.recipeId,servings:r.servings||1});else append_(SHEETS.PLANNER,{id:Utilities.getUuid(),weekStart:p.weekStart,day:p.day,meal:p.meal,recipeId:p.recipeId,servings:r.servings||1});return true},removeMeal:p=>{const x=rows_(SHEETS.PLANNER).find(r=>r.id===p.id);if(x)delRow_(SHEETS.PLANNER,x.__row);return true},updateMeal:p=>{const x=rows_(SHEETS.PLANNER).find(r=>r.id===p.id);if(x)update_(SHEETS.PLANNER,x.__row,{servings:p.servings});return true},generateMealPlan:generateMealPlan_,
 getShopping:p=>rows_(SHEETS.SHOPPING).filter(x=>String(x.weekStart)===String(p.weekStart)).map(x=>({...x,done:bool_(x.done),quantity:Number(x.quantity)||x.quantity})),toggleShopping:p=>{const x=rows_(SHEETS.SHOPPING).find(r=>r.id===p.id);if(x)update_(SHEETS.SHOPPING,x.__row,{done:!!p.done});return true},buildShoppingSmart:buildShopping_
};